services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: guardian-api
    environment:
      SUPABASE_URL: "${SUPABASE_URL}"
      SUPABASE_SERVICE_ROLE_KEY: "${SUPABASE_SERVICE_ROLE_KEY}"
      GUARDIAN_API_KEYS: "${GUARDIAN_API_KEYS}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      GEMINI_MODEL: "${GEMINI_MODEL:-models/gemini-pro-latest}"
      GEMINI_ENRICHMENT_ENABLED: "${GEMINI_ENRICHMENT_ENABLED:-False}"
      GEMINI_INCLUDE_ERROR_IN_RESPONSE: "${GEMINI_INCLUDE_ERROR_IN_RESPONSE:-False}"
      RATE_LIMIT_ENABLED: "${RATE_LIMIT_ENABLED:-True}"
      REDIS_URL: "redis://redis:6379/0"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: guardian-redis